### ISSUE TITLE
Démarrage automatique

### ISSUE THREAD

**Issue by pleboeuf** [pleboeuf/ErabliCollecteur#23]
Démarrage automatique du collecteur au démarrage de l'ordinateur. Le dashboard doit lui aussi ^tre démarrer par la même occasion.

**Comment by pleboeuf** [comment]
J'ai installé des script de démarrage automatique pour ErabliCollecteur et ErabliDash mais ils ne semblent pas toujours fonctionner automatiquement au démarrage.

**Comment by elecnix** [comment]
Ubuntu 15.10 utilise systemd: https://doc.ubuntu-fr.org/creer_un_service_avec_systemd

Je ne suis pas familier avec. La commande `sudo systemctl status` montre les deux applications, mais je ne pense pas que ça signifie que ça soit configuré pour le démarrage automatique.

Je vais tester sur une VM Ubuntu 15.10.

**Comment by pleboeuf** [comment]
Le système utilise maintenant Ubuntu 16.04. Des services ont été définit pour les éléments suivant du système:
- ErabliCollecteur
- ErabliDash
- ErabliExport
-ErabliWatchDog

C'est services démarrent automatiquement avec la machine.
